from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent

PUBLISHED = [
    ".python-version",
    "pyproject.toml",
    "uv.lock",
    "claims-provenance-review.json",
    "candidate-03-mechanical-check.json",
    "copy-validation-final.json",
    "candidate-delta-02-to-03.json",
    "checker-correction-01.json",
    "review_bundle.py",
    "validate_copies.py",
    "compare_candidates.py",
    "run_logged.py",
    "make_publication_manifest.py",
    "logs/candidate-03-mechanical-01.json",
    "logs/candidate-03-mechanical-01.stdout.bin",
    "logs/candidate-03-mechanical-01.stderr.bin",
    "logs/copy-validation-04.json",
    "logs/copy-validation-04.stdout.bin",
    "logs/copy-validation-04.stderr.bin",
    "logs/candidate-delta-01.json",
    "logs/candidate-delta-01.stdout.bin",
    "logs/candidate-delta-01.stderr.bin",
    "copy-validation.json",
    "logs/copy-validation-01.json",
    "logs/copy-validation-01.stdout.bin",
    "logs/copy-validation-01.stderr.bin",
]

EXTERNAL = [
    ("reviewed_bundle", "D:/CodexWorkspaces/mathematics-atlas/project/.codex/evidence/runs/msc-classification-v1/bundle.json"),
    ("identical_staging_candidate", "D:/CodexWorkspaces/mathematics-atlas/msc-product-work/bundle-final-candidate-03.json"),
    ("claim_locator_correction", "D:/CodexWorkspaces/mathematics-atlas/msc-product-work/claim-locator-correction-03.json"),
    ("source_audit", "D:/CodexWorkspaces/mathematics-atlas/project/evidence/msc-classification/source-review/final-audit.json"),
    ("adapter_audit", "D:/CodexWorkspaces/mathematics-atlas/project/evidence/msc-classification/adapter-review/final-audit.json"),
    ("product_audit", "D:/CodexWorkspaces/mathematics-atlas/project/evidence/msc-classification/product-review/final-msc-product-audit.json"),
    ("product_audit_manifest", "D:/CodexWorkspaces/mathematics-atlas/project/evidence/msc-classification/product-review/publication-manifest.json"),
    ("product_audit_seal", "D:/CodexWorkspaces/mathematics-atlas/project/evidence/msc-classification/product-review/review-seal.json"),
    ("verification_document", "D:/CodexWorkspaces/mathematics-atlas/project/docs/subject-browser-verification.md"),
    ("retained_source_license", "D:/CodexWorkspaces/mathematics-atlas/project/data/msc/LICENSE-CC-BY-NC-SA-4.0.md"),
    ("root_gate_03_record", "D:/CodexWorkspaces/mathematics-atlas/msc-product-work/gate-logs/attempt-msc-gate-03.json"),
    ("root_gate_03_stdout", "D:/CodexWorkspaces/mathematics-atlas/msc-product-work/gate-logs/attempt-msc-gate-03.stdout.bin"),
]


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def record(path: Path, display: str) -> dict[str, object]:
    return {"path": display, "bytes": path.stat().st_size, "sha256": digest(path)}


def main() -> None:
    copies = [record(ROOT / rel, rel) for rel in PUBLISHED]
    external = []
    for role, raw in EXTERNAL:
        path = Path(raw)
        row = record(path, raw)
        row["role"] = role
        external.append(row)
    manifest = {
        "schema_version": "independent-msc-promotion-publication-manifest-v1",
        "reviewer": "/root/sol_symmetry_worker",
        "recommendation": "PASS_FOR_SCOPED_MSC_PROMOTION_EVIDENCE",
        "reviewed_bundle_sha256": "f57ccfddf20064d1df481e289925f09b66657ce604f1047d8dce8ba9ba8d9e49",
        "unresolved_findings": 0,
        "copy_records": copies,
        "external_evidence_records": external,
        "excluded": [
            {"pattern": ".venv/**", "reason": "disposable isolated runtime"},
            {"pattern": "**/__pycache__/**", "reason": "generated bytecode"},
            {"pattern": "draft-mechanical-check.json and candidate-mechanical-check.json", "reason": "candidate 03 supersedes draft and candidate 02 mechanical results"},
            {"pattern": "copy-validation-02.json, copy-validation-03.json and their logs", "reason": "intermediate corrected passes superseded by the final expanded copy check"},
            {"pattern": "remaining exploratory command outputs", "reason": "the compact packet retains the failed attempt, correction, and final canonical checks"}
        ],
        "manifest_self_hash": "excluded because a file cannot contain its own cryptographic digest"
    }
    output = ROOT / "publication-manifest.json"
    output.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "path": str(output),
        "bytes": output.stat().st_size,
        "sha256": digest(output),
        "copy_records": len(copies),
        "external_evidence_records": len(external),
    }, indent=2))


if __name__ == "__main__":
    main()
