'use client';
import { useState } from 'react';
import { ArrowUpRight, BookOpen, Check, GitBranch, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { atlas, nodeById, sourceById, searchNodes } from '@/lib/atlas';
const colors: Record<string, string> = { foundations: '#72b7ff', physics: '#ffb573', probability: '#bd9bff', algorithms: '#5bdbc4', applications: '#f09abf' };
export default function Home() {
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState('laplacian');
  const node = nodeById[selected];
  const results = searchNodes(query);
  const connections = atlas.edges.filter(e => e.from === selected || e.to === selected);
  const nearby = new Set([selected, ...connections.flatMap(e => [e.from, e.to])]);
  return <main className="atlas-shell">
    <header className="atlas-header"><a className="brand" href="/"><span className="brand-mark"><GitBranch size={21}/></span><span>Mathematics<span className="brand-light"> Atlas</span></span></a><span className="scope-label">LAPLACIANS & NETWORKS</span><a className="repo-link" href="https://github.com/Legedith/maths" target="_blank" rel="noreferrer">Contribute <ArrowUpRight size={15}/></a></header>
    <div className="workspace">
      <aside className="catalogue"><div className="catalogue-heading"><h1>Explore connections</h1><p>Start with an idea. See where it leads.</p></div><div className="search-box"><Search size={18}/><Input aria-label="Search mathematical concepts" placeholder="Search a concept or problem…" value={query} onChange={e => setQuery(e.target.value)}/></div><div className="list-heading"><span>IN THIS REGION</span><span>{results.length} concepts</span></div><div className="concept-list">{results.map(({node:n}) => <button key={n.id} className={`concept-row ${n.id===selected?'active':''}`} onClick={() => setSelected(n.id)}><span className="domain-dot" style={{background:colors[n.cluster]}}/><span><strong>{n.label}</strong><small>{n.domains.join(' · ')}</small></span><span className="row-arrow">↗</span></button>)}{!results.length&&<p className="no-results">No match in this region. A search miss does not mean the idea is unknown.</p>}</div><div className="coverage-note"><BookOpen size={18}/><div><strong>A growing map</strong><p>This first region covers Laplacians and networks. Other areas are still to be mapped.</p></div></div></aside>
      <section className="map-panel" aria-label="Interactive concept map"><div className="map-topline"><span><span className="live-dot"/> {atlas.nodes.length} concepts · {atlas.edges.length} connections</span><span>Choose a node to follow its connections</span></div><svg className="knowledge-graph" viewBox="0 0 940 660" role="img" aria-label="Connections between the graph Laplacian, electrical networks and spanning trees"><defs><pattern id="dots" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#27364a"/></pattern></defs><rect width="940" height="660" fill="url(#dots)"/>{atlas.edges.map(e => {const a=nodeById[e.from],b=nodeById[e.to],active=e.from===selected||e.to===selected;return <line key={e.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={active?'#779abd':'#304359'} strokeWidth={active?2:1} strokeDasharray={e.status==='proposed'?'5 5':undefined}/>;})}{atlas.nodes.map(n => <g key={n.id} className="map-node" role="button" tabIndex={0} aria-label={`Explore ${n.label}`} aria-pressed={selected===n.id} onClick={() => setSelected(n.id)} onKeyDown={e => {if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(n.id);}}} opacity={nearby.has(n.id)?1:.5}><circle cx={n.x} cy={n.y} r={selected===n.id?32:22} fill={selected===n.id?colors[n.cluster]:'#111f32'} stroke={colors[n.cluster]} strokeWidth={selected===n.id?3:2}/><circle cx={n.x} cy={n.y} r="5" fill={selected===n.id?'#102039':colors[n.cluster]}/><text x={n.x} y={n.y+47} textAnchor="middle" fill="#ebf1fa" fontSize="16" fontWeight={selected===n.id?650:450}>{n.label}</text></g>)}</svg><div className="map-legend">{Object.entries(colors).slice(0,4).map(([name,color])=><span key={name}><i style={{background:color}}/>{name}</span>)}</div><div className="map-caption">Every line has a meaning. Inspect it in the connection panel.</div></section>
      <aside className="detail-panel" aria-live="polite"><div className="detail-top"><span className="eyebrow">{node.domains.join(' / ')}</span><span className="sourced"><Check size={13}/> Sourced</span></div><h2>{node.label}</h2><p className="node-summary">{node.summary}</p>{node.formula&&<div className="formula">{node.formula}</div>}<p className="explanation">{node.explanation}</p><h3>Connections to follow <span>{connections.length}</span></h3>{connections.map(e=>{const other=nodeById[e.from===selected?e.to:e.from];return <div key={e.id} className="connection"><Button variant="link" className="connection-title" onClick={()=>setSelected(other.id)}>{other.label}<ArrowUpRight size={15}/></Button><span className="relation-type">{e.type.replaceAll('_',' ')}</span><p>{e.statement}</p><details><summary>Assumptions & source</summary><ul>{e.assumptions.map(a=><li key={a}>{a}</li>)}</ul>{e.evidence.map((v,i)=><a key={i} href={sourceById[v.source].url} target="_blank" rel="noreferrer">{sourceById[v.source].author} · {v.locator} ↗</a>)}</details></div>;})}<h3>Read the source</h3>{node.evidence.map((v,i)=><a className="source-link" key={i} href={sourceById[v.source].url} target="_blank" rel="noreferrer"><BookOpen size={17}/><span>{sourceById[v.source].title}<small>{sourceById[v.source].author} · {v.locator}</small></span><ArrowUpRight size={15}/></a>)}</aside>
    </div>
  </main>;
}
