from pathlib import Path
import hashlib,json
from html.parser import HTMLParser
P=Path('D:/CodexWorkspaces/mathematics-atlas/project');S=Path(__file__).parent;B=P.parent
bp=P/'.codex/evidence/runs/novelty-investigation-v1/bundle.json';bundle=json.loads(bp.read_bytes())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(bp)=='03e80d0b039dd2131af3bdf5379761930da66cbcab8e8aee6406ab6a18f7eecb'
for name,d in [('certificate.json','b264e53aa98bb9171fcb327cb82cd01ec31e4c67eecbf30af6752545c078804c'),('verify_certificate.py','7b656d33739a7a77834d1ae47f8115cd830f04bb05638a68a8de73189f747749')]:assert sha(P/'experiments/kemeny-multipartite-proof'/name)==d
assert sha(B/'novelty-portable-review-work/review.md')=='3717ce388e1dcc9460486e4ff4f5d89a54440710783ebf72cbfe5eec2d90af8d'
class Parser(HTMLParser):
 def __init__(self):super().__init__();self.stack=[];self.errors=[]
 def handle_starttag(self,t,a):
  if t not in {'meta','link','br','hr','img','input','source','area','base','col','embed','param','track','wbr'}:self.stack.append(t)
 def handle_endtag(self,t):
  if not self.stack or self.stack.pop()!=t:self.errors.append(t)
h=Parser();h.feed((P/'docs/index.html').read_text(encoding='utf-8'));assert not h.stack and not h.errors
log=json.loads((S/'logs/attempt-render-review01.json').read_bytes());assert log['returncode']==0 and not log['timed_out'] and log['timeout_seconds']==90
for stream in ['stdout','stderr']:
 p=S/'logs'/log[stream]['path'];assert sha(p)==log[stream]['sha256'] and p.stat().st_size==log[stream]['bytes']
checks=[dict(id='reproduction',status='pass',auditor='independent Astra final reviewer',evidence=['A006','A007','A008','A011','A027','A033','A037','A043','A049','A051','A053','A057','A058','A062','A063','A064','A068'],note='Six canonical raw logs and stream hashes validated. Main outputs byte-equal prior audited outputs. All89 portable rows equal author, and k/K/delta equal independent reviewer. One<=90s in-memory renderer replay through uv process-tree logger rc0/empty stderr produced identical HTML and build metrics. Mathematical evaluators not rerun.'),dict(id='specification_compliance',status='pass',auditor='independent Astra final reviewer',evidence=['A001','A013','A018','A022','A023','A070','A118','A119','A128','A130'],note='Central result is exact r>=3 positive-p conjecture clause, all minimum ties, single unweighted insertion. Proof finite-support extension explicit. Ranking secondary strengthening and correction subsidiary. Novelty is against inspected literature, no first/exhaustive priority, Lean, journal-review or measured impact claim. Publication separate.'),dict(id='source_verification',status='pass',auditor='independent Astra final reviewer',evidence=['A004','A044','A100','A105','A113','A118','A119','A121','A128'],note='All147 artifact hashes and17 claims/145 recursive supports checked. Primary-return retention hashes checked against local bytes. Accepted distinct source and bridge audits cover original conjecture and later completion/tree/twin-clique scopes. Corrected bridge ACK closes P2 typo; original failure retained. SourceExample and corrected89-row result match inspected version-specific statement.'),dict(id='implementation_alignment',status='pass',auditor='independent Astra final reviewer',evidence=['A002','A003','A005','A009','A010','A012','A032','A044','A128','A129','A132','A133','A135','A136','A137','A138','A139','A140','A141','A142','A143','A144'],note='Final equations/domain/eigenmodes/finite-support proof align with accepted audits and actual code. Distinct portable-adaptation review3717ce38... read and hash checked. Workflow logger/uv/cap/upload paths inspected; no hosted success inferred. HTML source equality/nesting/links/assets static checks pass. Three-ref publication plan keeps codex/research-paper links aligned. Explicit certificate/checker final ledger entries required as metadata correction.')]
v=dict(status='corrections',semantic_status='pass',input_bundle_sha256=sha(bp),checks=checks,required_corrections=['Add explicit hashed artifacts for experiments/kemeny-multipartite-proof/certificate.json and verify_certificate.py, plus distinct portable/final reviews and publication-plan. Preserve reviewed source bytes, rerun deterministic gate, and obtain final-bundle metadata/hash acknowledgement before push.'],limitations=['Local integration only; actual final-head CI and hosted publication require post-push audit.','No new mathematical evaluator or browser interaction; one read-only renderer replay.','No exhaustive priority, first-proof, Lean, external journal-review or field-impact certification.'])
(S/'verdict.json').write_text(json.dumps(v,indent=2)+'\n',encoding='utf-8')
report='''# Independent final integration audit, round 1

Semantic four-gate PASS. One final metadata correction remains: explicitly include the promoted certificate.json and verify_certificate.py in the ledger, together with the portable/final reviews and publication plan, then rerun the deterministic gate and obtain the final-bundle acknowledgement. No manuscript/code correction is required. Input bundle SHA256 `'''+sha(bp)+'''`.

All147 artifact hashes and17 claims were checked through145 recursive support locators, including expected JSON values and cycle checks. Six canonical command records match their raw stream hashes. Main polynomial/ranking outputs byte-match the earlier independently audited outputs. All89 portable correction rows match author output, and every k/K/delta matches the distinct independent reconstruction. Source-retention files resolve to matching local raw bytes; public evidence contains notes/requests/hashes rather than bulk third-party returns. The retained initial locator failure and case-sensitive JSON resolution are transparent and not used as a passing gate.

The final README matches the accepted all-r sign proof, strict ranking argument, corrected clique formula and finite example. Full-part notation explicitly includes singleton vertices. The weighted-degree bound is stated before the finite-support argument, with part count independent of the formal gap count. The source theorem and conjecture scopes are distinguished: r>=3,p>=1,q_i>=3; size2 and p0 cases are not silently included; every tied minimum and every within-part pair are covered. Ranking does not establish repeated greedy validity. The 2026 correction accounts for quotient modes and the empty-cell boundary; all89 integer orders give unique28. The source's printed simplification and stated33 example are precisely the subsidiary correction, not central novelty.

The separate portable-adaptation reviewer inspected the actual CLI/math loop and confirms unchanged mathematical content, exclusive output, pinned runtime and static CI wiring (review SHA3717ce388e1dcc9460486e4ff4f5d89a54440710783ebf72cbfe5eec2d90af8d). I additionally checked the actual code/output hash, raw logs and all rows. Existing main checkers remain unchanged. Certificate SHAb264e53aa98bb9171fcb327cb82cd01ec31e4c67eecbf30af6752545c078804c and checker SHA7b656d33739a7a77834d1ae47f8115cd830f04bb05638a68a8de73189f747749 were independently checked and must become explicit final bundle artifacts.

One in-memory renderer replay replaced only the two shared output writes with byte assertions; execution used uv outer/child and the existing process-tree logger, cap90s, rc0, empty stderr. Generated bytes and metrics equal the canonical page. HTML nesting, fragment/local links, assets and metadata pass static checks. Responsive/print styles, skip link, labeled navigation and native button remain. No browser interaction or visual-rendering certification is made. Repository links deliberately target codex/research-paper; the separately frozen publication plan atomically fast-forwards that branch, default codex/atlas-foundation and working codex/novelty-investigation to one commit. Actual heads and hosted bytes remain post-push obligations.

The final source/contribution wording preserves the approved reasoned originality assessment against inspected literature and avoids a first-proof claim. A named conjecture plus exact full-domain proof and closest-source comparison supplies affirmative support; a negative search alone does not. Ranking is a separately proved strengthening, not independently advertised as substantial novelty. No Lean formalization, external peer review, universal field impact or complete-atlas claim is made.

Four typed checks with bundle IDs are in verdict.json; complete reviewed artifact hashes, added dependency hashes and raw renderer logs are retained in manifest.json. A hash-only finalization acknowledgement is sufficient if only the requested ledger/review additions change and all reviewed artifact bytes remain identical.
'''
(S/'review.md').write_text(report,encoding='utf-8')
extra=[P/'experiments/kemeny-multipartite-proof/certificate.json',P/'experiments/kemeny-multipartite-proof/verify_certificate.py',B/'novelty-portable-review-work/review.md',B/'novelty-portable-review-work/verdict.json',B/'novelty-portable-review-work/hashes.json',B/'novelty-paper-work/publication-plan.md',bp]
extra+=sorted(p for p in S.rglob('*') if p.is_file() and p.name!='manifest.json')
(S/'manifest.json').write_text(json.dumps(dict(input_bundle_sha256=sha(bp),bundle_artifacts=bundle['artifacts'],extra_artifacts=[dict(path=str(p),sha256=sha(p),bytes=p.stat().st_size) for p in extra]),indent=2)+'\n',encoding='utf-8')
print(json.dumps(dict(status='corrections',semantic_status='pass',required_corrections=v['required_corrections'])))
